import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import axios from'axios';import'./style.css';
const api=axios.create({baseURL:'http://localhost:3001'});
function App(){const[token,setToken]=useState(localStorage.token||'');const[user,setUser]=useState(JSON.parse(localStorage.user||'null'));const[clientes,setClientes]=useState([]);const[aniv,setAniv]=useState([]);const[form,setForm]=useState({});api.defaults.headers.common.Authorization=token?'Bearer '+token:'';
async function login(e){e.preventDefault();const r=await api.post('/login',form);localStorage.token=r.data.token;localStorage.user=JSON.stringify(r.data.usuario);setToken(r.data.token);setUser(r.data.usuario)}
async function carregar(){setClientes((await api.get('/clientes')).data);setAniv((await api.get('/aniversariantes/hoje')).data)}
async function salvarCliente(e){e.preventDefault();await api.post('/clientes',form);setForm({});carregar()}
async function addProduto(id){const ambiente=prompt('Ambiente/produto:');const valor=Number(prompt('Valor:'));if(ambiente&&valor) {await api.post(`/clientes/${id}/produtos`,{ambiente,valor,status:'orçamento'});carregar()}}
useEffect(()=>{if(token)carregar()},[token]);
if(!token)return <main className="login"><form onSubmit={login}><h1>CRM Móveis Planejados</h1><input placeholder="email" onChange={e=>setForm({...form,email:e.target.value})}/><input placeholder="senha" type="password" onChange={e=>setForm({...form,senha:e.target.value})}/><button>Entrar</button><small>Admin inicial: admin@empresa.com / 123456</small></form></main>;
return <main><header><h1>CRM Móveis Planejados</h1><button onClick={()=>{localStorage.clear();location.reload()}}>Sair</button></header><section className="cards"><div><b>{clientes.length}</b><span>Clientes</span></div><div><b>{aniv.length}</b><span>Aniversariantes hoje</span></div><div><b>R$ {clientes.reduce((s,c)=>s+c.ticket_total,0).toLocaleString('pt-BR')}</b><span>Total orçado</span></div></section><section><h2>Novo cliente</h2><form className="grid" onSubmit={salvarCliente}>{['nome','data_nascimento','cpf','rg','telefone','email','endereco','observacoes'].map(c=><input key={c} type={c==='data_nascimento'?'date':'text'} placeholder={c.replace('_',' ')} value={form[c]||''} onChange={e=>setForm({...form,[c]:e.target.value})}/>)}<button>Salvar cliente</button></form></section><section><h2>Aniversariantes de hoje</h2>{aniv.map(c=><div className="item" key={c.id}><b>{c.nome}</b><p>{c.mensagem}</p></div>)}</section><section><h2>Clientes</h2><table><thead><tr><th>Nome</th><th>Telefone</th><th>Vendedor</th><th>Ticket</th><th></th></tr></thead><tbody>{clientes.map(c=><tr key={c.id}><td>{c.nome}</td><td>{c.telefone}</td><td>{c.vendedor_nome}</td><td>R$ {Number(c.ticket_total).toLocaleString('pt-BR')}</td><td><button onClick={()=>addProduto(c.id)}>+ produto</button></td></tr>)}</tbody></table></section></main>}
createRoot(document.getElementById('root')).render(<App/>);
